### PR TITLE
Maxwell scatterplot

### PR DESCRIPTION
**Pull request by lilyclements**
Made minor design changes. @maxwellfundi this is ready for you to merge

It says 8 files changed, but I only changed the scatterplot code and design. My branch was just more updated than yours

### CODE REVIEW

**Comment by maxwellfundi** [comment]
Why are we having all these commits @lilyclements ?

**Comment by lilyclements** [comment]
Because my branch was updated to the master copy and yours wasn't so it's updating your one to the master branch too if you merge it in

**Comment by maxwellfundi** [comment]
Okay, I then will accept it. 

About the other issue, did you understand why i did that?

Thanks.

**Comment by lilyclements** [comment]
Which other issue? The testOk?

**Comment by maxwellfundi** [comment]
Why i changes the test okay

**Pull request merged**
