### PR TITLE
Designer edits

### PR DESCRIPTION
**Pull request by lilyclements**
@maxwellfundi have a look, this should be ready. I'm not sure why my designer edits have edited on the resources file though - is this where the designer edits occur now?

### CODE REVIEW

**Comment by lilyclements** [comment]
Hold on, just going to edit the sub dialog for Parcoord then it'll be ready!

**Comment by maxwellfundi** [comment]
Yes the resource file is edited every time you you edit the designer

**Comment by lilyclements** [comment]
Okay that's new! Thanks :) sending up parcoord edits plus parameter position changes soon, also noticed a testOK bug so fixing that

**Review by lilyclements — COMMENTED** [review]
@maxwellfundi this is ready. Take a look. I'm not sure what has changed coding wise over the past few months of course!

**Pull request merged**
